### ISSUE TITLE
Jump to label feature

### ISSUE THREAD

**Issue by maarzt** [maarzt/imglib2-labkit#13]
It might be hard to find the labels, if only small regions in a huge image are labeled.

A functionality jump to the labeled region should be implemented.

**Comment by maarzt** [comment]
Class OrthogonalView shows how the viewer transformation can be (re)set:
https://github.com/maarzt/imglib2-labkit/blob/master/src/main/java/net/imglib2/labkit/actions/OrthogonalView.java

**Comment by frauzufall** [comment]
implemented https://github.com/maarzt/imglib2-labkit/pull/17
