### ISSUE TITLE
Add progress bar

### ISSUE THREAD

**Issue by maarzt** [maarzt/imglib2-labkit#4]
When training a classifier, the user can not notice that something happens. A progress bar or something like this would be nice during training.

**Comment by imagejan** [comment]
You should be able to simply call the SciJava [`StatusService`](http://javadoc.scijava.org/SciJava/index.html?org/scijava/app/StatusService.html):

    statusService.showProgress(50, 100);

**Comment by maarzt** [comment]
I dialog that shows during training was implemented.
