### ISSUE TITLE
Bug: Progress dialog gains focus all the time

### ISSUE THREAD

**Issue by haesleinhuepf** [maarzt/imglib2-labkit#45]
Hi @maarzt ,

I was just trying to export a segmented stack. This popup show up:
![image](https://user-images.githubusercontent.com/12660498/82242028-71d41280-993d-11ea-9457-7b1c7c6c20e8.png)

Unfortunately, this dialog gains the focus all the time repeatedly. I can't use my computer anymore. Can this focus-thingy be disabled?

Thanks!

Cheers,
Robert

**Comment by maarzt** [comment]
This is fixed by now.
