### ISSUE TITLE
Color button on mac

### ISSUE THREAD

**Issue by maarzt** [maarzt/imglib2-labkit#5]
The button to change the labels color on mac is very ugly. Make it nicer

**Comment by imagejan** [comment]
How about re-using the SciJava [`ColorWidget`](https://github.com/scijava/scijava-common/blob/master/src/main/java/org/scijava/widget/ColorWidget.java), so that all consumers of this widget can benefit from potential UI improvements?

**Comment by maarzt** [comment]
done https://github.com/maarzt/imglib2-labkit/commit/2fa6ea2de7c7161d8488d0f75127e12e32bcc675
